In [2]:
# Copy

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("After creating array: ", arr)

new_arr = arr.copy()
print("After making copy:", new_arr)

new_arr[0] = 10
print("After changing the new_arr:", new_arr)
print("Orignal arr:", arr)

After creating array:  [1 2 3 4 5]
After making copy: [1 2 3 4 5]
After changing the new_arr: [10  2  3  4  5]
Orignal arr: [1 2 3 4 5]


In [3]:
# View

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("After creating array: ", arr)

new_arr = arr.view()
print("After making view:", new_arr)

new_arr[0] = 10
print("After changing the new_arr:", new_arr)
print("Orignal arr:", arr)

After creating array:  [1 2 3 4 5]
After making view: [1 2 3 4 5]
After changing the new_arr: [10  2  3  4  5]
Orignal arr: [10  2  3  4  5]


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

new_arr_copy = arr.copy()
new_arr_view = arr.view()

print(new_arr_copy.base)
print(new_arr_view.base)

None
[1 2 3 4 5]


In [8]:
# it print the dimantion of the array (shape), how much rows and coloumns are exist
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)

(5,)


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
