In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

# iterate 1D array
for item in arr:
    print(item)
    

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# iterate 2D array
for item in arr:
    print(item)
    

[1 2 3]
[4 5 6]
[7 8 9]


In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# iterate 2D array with single element
for i in range(len(arr)):
    print("row", i)
    for j in range(len(arr[i])):
        print("column", j, "==", arr[i, j])
    print("")
    

row 0
column 0 == 1
column 1 == 2
column 2 == 3

row 1
column 0 == 4
column 1 == 5
column 2 == 6

row 2
column 0 == 7
column 1 == 8
column 2 == 9



In [25]:
import numpy as np
arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [11, 12, 13]]
])

# iterate 3D array with single element
for block in arr:
    print("block", block)
    print("")
    for inner_arr in block:
        print("inner arr",inner_arr)
    
    print("------------------------")
        
        

block [[1 2 3]
 [4 5 6]]

inner arr [1 2 3]
inner arr [4 5 6]
------------------------
block [[ 7  8  9]
 [11 12 13]]

inner arr [7 8 9]
inner arr [11 12 13]
------------------------


In [14]:
import numpy as np
arr = np.array([
    [[1, 2, 3], 
     [4, 5, 6]], 
    [[7, 8, 9], 
     [11, 12, 13]]
])

# iterate 2D array with single element
for i in range(len(arr)):
    print("row", i)
    for j in range(len(arr[i])):
        print("column", j, "==", arr[i, j])
    print("")
    

row 0
column 0 == [1 2 3]
column 1 == [4 5 6]

row 1
column 0 == [7 8 9]
column 1 == [11 12 13]



In [34]:
import numpy as np
arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [11, 12, 13]]
])

# iterate 3D array with single element
for index1, block in enumerate(arr):
    print("block", index1, block)
    print("")
    for index2, inner_arr in enumerate(block):
        print("Inner Array", index2, inner_arr)

        for index3, inner_arr_in_inner in enumerate(inner_arr):
            print(index3, "=", inner_arr_in_inner)
            
        print("********************")
    
    print("------------------------")
        
        

block 0 [[1 2 3]
 [4 5 6]]

Inner Array 0 [1 2 3]
0 = 1
1 = 2
2 = 3
********************
Inner Array 1 [4 5 6]
0 = 4
1 = 5
2 = 6
********************
------------------------
block 1 [[ 7  8  9]
 [11 12 13]]

Inner Array 0 [7 8 9]
0 = 7
1 = 8
2 = 9
********************
Inner Array 1 [11 12 13]
0 = 11
1 = 12
2 = 13
********************
------------------------


In [35]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [36]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)
  

1
3
5
7
