In [11]:
# import numpy

# decleare the array
array = numpy.array([1, 2, 3, 4, 5])
print(array)

print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
# pass the tuple in the array
array = numpy.array((10, 20, 30, 40)) 
print(array)

[10 20 30 40]


In [15]:
# pass the list in tuple
array = numpy.array([90, 80, 70, 60])
print(array)

[90 80 70 60]


In [17]:
# 0-D array
array = numpy.array(80)
print(array)

80


In [19]:
# 1-D array
array = numpy.array(["ankit", "sourabh", "rishabh", "Shrawan"])
print(array)

['ankit' 'sourabh' 'rishabh' 'Shrawan']


In [20]:
# 2-D array
array = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# 3-D array
array = numpy.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(array)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [22]:
# ndim is a attribute that gives us how many diantions of the array

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) # 0-D
print(b.ndim) # 1-D
print(c.ndim) # 2-D
print(d.ndim) # 3-D

0
1
2
3


In [24]:
import numpy as np
arr1 = np.array([10, 20, 30, 40], ndmin = 5)

print(arr1)
print("Dimntions: ", arr1.ndim)

[[[[[10 20 30 40]]]]]
Dimntions:  5


In [27]:
import numpy as np

# access array element by the index
array = np.array([10, 20, 30, 40])
print(array[0])


10


In [28]:
import numpy as np

# access two element and add
arrray = np.array([10, 20, 30, 40])
print(array[0] + array[3])

50


In [38]:
import numpy as np

# access element from 2-D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array[0, 1])

import numpy as np

# access element from 3-D array
array1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(array1[0, 2, 1])

2
8


In [34]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 0, 1])

8


In [40]:
# nagative indexing

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -2])

Last element from 2nd dim:  9


In [46]:
import numpy as np

# sclicing on the array
arr = np.array([10, 20, 30, 40])
print("sclicing", arr[0:2])

sclicing [10 20]


In [48]:
import numpy as np

# nagative sclicing on the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("sclicing", arr[-3:-1])

sclicing [5 6]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6:2])

[2 4 6]


In [1]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [5]:
import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

print(arr[0, 2])

print(arr[1, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
4


In [8]:
import numpy as np

arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

second_row = arr[1]
print("Second Row:")
print(second_row)

Second Row:
[5 6 7 8]


In [9]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6])
sum1 = np.sum(arr)
print(sum1)

21


In [11]:
import numpy as np

arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9, 10, 11, 12]])

# Your code to compute the sum of all elements in arr goes here
sum2 = np.sum(arr)
print(sum2)

78


In [13]:
# create 1D array

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [14]:
# Access elemenet

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])

3


In [48]:
# sclicing

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[2 : 4])

[3 4]


In [16]:
# iterate with for loop

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

for i in arr:
    print(i)

1
2
3
4
5


In [17]:
# find length

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(len(arr))

5


In [21]:
# find even number

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

for i in arr:
    if i % 2 == 0:
        print(i)
    

2
4


In [22]:
# iterate with while loop

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
i = 0

while i < len(arr):
    print(arr[i])
    i += 1
    

1
2
3
4
5


In [54]:
# insert new element in array

import numpy as np
arr = np.array([1, 2, 3])

new_row = np.array([10, 11, 12])
arr_with_new_row = np.insert(arr, 0, new_row, axis=0)
print(arr_with_new_row)

[10 11 12  1  2  3]


In [56]:
# insert new element in array

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

arr_with_delete_column = np.delete(arr, 0)
print(arr_with_delete_column)

[2 3 4 5]


In [23]:
# create 2D array

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# access element

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr[0, 2])
print(arr[2, 0])

3
7


In [29]:
# sclicing

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr[0, 0 : 2])
print(arr[2, 1 : 3])

[1 2]
[8 9]


In [47]:
# sclicing

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr[0 : 2, 2])
# print(arr[2, 1 : 3])

[3 6]


In [30]:
# iterate by for loop

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [31]:
# even number by for loop

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

for i in arr:
    for j in i:
        if j % 2 == 0:
            print(j)

2
4
6
8


In [38]:
# iterate by while loop

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

i = 0
while i < len(arr):
    for j in arr[i]:
        print(j)
    i += 1


1
2
3
4
5
6
7
8
9


In [42]:
# insert new row

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

new_row = np.array([10, 11, 12])
arr_with_new_row = np.insert(arr, 3, new_row, axis = 0)
print(arr_with_new_row)

            

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
# insert new coloumn

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

new_column = np.array([10, 11, 12])
arr_with_new_row = np.insert(arr, 3, new_row, axis = 1)
print(arr_with_new_row)

            

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [53]:
# delete coloumn

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr_with_delete_coloumn = np.delete(arr, 2, axis = 1)
print(arr_with_delete_coloumn)

            

[[1 2]
 [4 5]
 [7 8]]


In [57]:
# delete row

import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr_with_delete_row = np.delete(arr, 2, axis = 0)
print(arr_with_delete_row)
            

[[1 2 3]
 [4 5 6]]


In [58]:
# create a 3D array
import numpy as np
arr = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])
print(arr)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [63]:
# access elemetn from the 3D array
import numpy as np
arr = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]])
print(arr[0, 0, 1])
print(arr[0, 2, 1])


2
8


In [6]:
# access elemetn from the 3D array
import numpy as np
arr = np.array([[
    [1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]
]])
print(arr[1, 0, 1])
print(arr[0, 1, 2])
# print(arr[0, 2, 1])


8
6


In [26]:
# access elemetn from the 3D array
import numpy as np
arr = np.array([[
    [1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]
]])

print(arr[0, 0, 2])

[]


In [11]:
# sclicing

import numpy as np
arr = np.array([[
    [1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]
]])

print(arr[1, 1 : 2])

[[10 11 12]]


In [31]:
import numpy as np
arr = np.array([
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

print(arr[1, 0, 1:3])

# sclicing


[14 15]


In [7]:
import numpy as np
arr = np.array([[[1, 2, 3, 4, 5, 6]]])

print(arr[0, 0, 3])

4


In [12]:
import numpy as np
arr = np.array([[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]])

print(arr[0, 0])

[1 2 3 4 5 6]


In [12]:
import numpy as np
arr = np.array([[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]])

print(arr[0, 0])

[1 2 3 4 5 6]


In [11]:
import numpy as np
arr = np.array([[[7, 8, 9], [10, 11, 12]], [13, 14, 15], [16, 17, 18]]])

print(arr[1, 0, 1])

14


In [19]:
import numpy as np
arr = np.array([
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

print(arr[1, 1, 1:3])

[17 18]


In [21]:
import numpy as np
arr = np.array([
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

for x in arr:
    for y in x:
        print(y)


[7 8 9]
[10 11 12]
[13 14 15]
[16 17 18]


In [21]:
import numpy as np
arr = np.array([
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])


[7 8 9]
[10 11 12]
[13 14 15]
[16 17 18]
