In [2]:
import numpy as np

# create a 1D arr
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [58]:
import numpy as np

# create a 1D arr
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# change the element for through the sclicing
arr[2:] = 10
print(arr)

[1 2 3 4 5]
[ 1  2 10 10 10]


In [3]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# access the element
print(arr[0, 0])
print(arr[0, 2])

1
3


In [15]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# insert the element
new_arr = np.insert(arr, 1, [7, 8, 9], axis = 0)
print(new_arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [18]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# delete the element
new_arr = np.delete(arr, 0, axis = 0)
print(new_arr)

[[4 5 6]]


In [17]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# delete the element
new_arr = np.delete(arr, 0)
print(new_arr)

[2 3 4 5 6]


In [22]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# scling the element
print(arr[0, 1:3])
print(arr[1, 0:2])

[2 3]
[4 5]


In [23]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# iterate
for ele in  arr:
    print(ele)

[1 2 3]
[4 5 6]


In [24]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6]])

# iterate
for ele in  arr:
    print(ele)
    for x in ele:
        print(x)



[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [25]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[2, :])

[7 8 9]


In [26]:
import numpy as np

# create a 2D arr
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:, 1])

[2 5 8]


In [30]:
import numpy as np

# find the dimantions 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.ndim(arr))

2


In [37]:
import numpy as np

# find the dimantions 
arr = np.array([1, 2, 3], ndmin = 5)
print(arr)
print(np.ndim(arr))

[[[[[1 2 3]]]]]
5


In [40]:
# create a 3D array
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
# create a 3D array
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]
])

# access element
print(arr[1, 0, 1])
print(arr[2, 0, 2])

8
15


In [45]:
# create a 3D array
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]
])

# sclicing
print(arr[1, 0, 1:])
print(arr[2, 1, :2])

[8 9]
[16 17]


In [49]:
# create a 3D array
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]
])

# sclicing
print(arr[1, 0:2, 1:3])


[[ 8  9]
 [11 12]]


In [60]:
# create a 3D array
import numpy as np

arr = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]
])

# change value with sclicing
arr[:, :, 1]= 10
print(arr)


[[[ 1 10  3]
  [ 4 10  6]]

 [[ 7 10  9]
  [10 10 12]]

 [[13 10 15]
  [16 10 18]]]


In [53]:
import numpy as np

# copy arr
arr = np.array([1, 2, 3, 4, 5])
print("Orignal array")
print(arr)
print("\n copied array")
new_arr = np.copy(arr)
print(new_arr)

Orignal array
[1 2 3 4 5]

copied array
[1 2 3 4 5]


In [56]:
import numpy as np

# copy arr
arr = np.array([1, 2, 3, 4, 5])
print("Orignal array")
print(arr)
print("\n copied array")
new_arr = np.copy(arr)
print(new_arr)

# changing the element of the copied array
new_arr[0] = 10
print("\nafter changing the value")
print(new_arr)

Orignal array
[1 2 3 4 5]

 copied array
[1 2 3 4 5]

after changing the value
[10  2  3  4  5]


In [63]:
import numpy as np

# View 
arr = np.array([1, 2, 3, 4, 5])
print("Orignal array")
print(arr)
print("\n copied array by View")
new_arr = arr.view()
print(new_arr)

# changing the element of the copied array
new_arr[0] = 10
print("\nafter changing the value new array")
print(new_arr)
print("\nafter changing the value original array")
print(arr)

Orignal array
[1 2 3 4 5]

 copied array by View
[1 2 3 4 5]

after changing the value new array
[10  2  3  4  5]

after changing the value original array
[10  2  3  4  5]


In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(np.shape(arr))

(5,)


In [70]:
# create a 3D array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# find the shape of the array
print(np.shape(arr))

(3, 3)


In [74]:
# create a 3D array
import numpy as np

arr = np.array([1, 2, 3], ndmin = 3)
# find the shape of the array
print(np.shape(arr))

(1, 1, 3)


In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr = np.reshape(2, 3)
print(new_arr)

ValueError: cannot reshape array of size 1 into shape (3,)