In [6]:
# Create a 1D array with numbers from 0 to 9.

import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Create a 2D array with shape (3, 3) filled with zeros.

import numpy as np

arr_2d = np.zeros((3, 3))
print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Create a 2D array with shape (4, 4) filled with ones.

arr_2d = np.ones((4, 4))
print(arr_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Create an array with numbers from 10 to 20.

import numpy as np
arr = np.arange(10, 21)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


In [12]:
# Create an array of 5 evenly spaced values between 0 and 1.






# we have to solve 

In [15]:
# Create a 1D array of 10 random integers between 0 and 100.

import numpy as np 
arr = np.random.randint(0, 101, size=10)
print(arr)

[ 7 38 76 75 24  1 15 37 23 33]


In [19]:
# Create a 3x3 identity matrix.

import numpy as np 



# not sumbitted

In [22]:
# Create a 1D array with 10 random floating-point numbers.

import numpy as np

arr = np.random.random(10)
print(arr)

[0.83599683 0.01435949 0.34270889 0.89882874 0.94456856 0.71567452
 0.63916011 0.49718712 0.46562738 0.40771971]


In [ ]:
# Create a 5x5 array with random values and find the maximum value.

import numpy as np
