In [1]:
# 1. Create a NumPy array:
# Create a 1D NumPy array with elements from 0 to 9.
import numpy as np

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# 2. Array Indexing:
# Given the array arr = np.array([10, 20, 30, 40, 50]), extract the third element.

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [3]:
# 3. Array Slicing:
# Given the array arr = np.arange(10), extract the sub-array consisting of the first 5 elements.

arr = np.arange(10)
print(arr[:5])

[0 1 2 3 4]


In [4]:
# 4. Basic Operations:
# Create two 1D arrays a and b with elements [1, 2, 3] and [4, 5, 6] respectively. Perform element-wise\
# addition, subtraction, multiplication, and division.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [5]:
# addition
print(a + b)

[5 7 9]


In [6]:
# subtraction
print(a - b)

[-3 -3 -3]


In [7]:
# multiplication
print(a * b)

[ 4 10 18]


In [8]:
# division
print(a / b)

[0.25 0.4  0.5 ]


In [9]:
# 5. Array Reshaping:
# Given the array arr = np.arange(12), reshape it into a 3x4 matrix.

arr = np.arange(12)
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# Given two 2D arrays A and B:

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [32]:
# 6. Matrix Multiplication:
print(A @ B)

[[19 22]
 [43 50]]


In [19]:
# 7. Boolean Masking:
# Given the array arr = np.array([10, 15, 20, 25, 30]), create a boolean mask to extract elements greater than 20.

arr = np.array([10, 15, 20, 25, 30])
mask = arr > 20
print(mask)

[False False False  True  True]


In [20]:
# 8. Statistical Operations:
# Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), compute the mean, median, and standard deviation.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



# skip

In [21]:
# 9. Stacking Arrays:
# Given two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), stack them vertically and horizontally.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [23]:
 # stack vertically
arr = np.vstack((a, b))
print(arr)

[[1 2 3]
 [4 5 6]]


In [24]:
# stack horizontally
arr = np.hstack((a, b))
print(arr)

[1 2 3 4 5 6]


In [31]:
# 10. Advanced Indexing:
# Given the 2D array arr:
# Extract the elements at the positions (0,0), (1,1), and (2,2).

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

90

In [27]:
# (0,0)
arr[0, 0]

10

In [28]:
# (1,1)

arr[1, 1]

50

In [29]:
# (2,2)
arr[2, 2]

90

In [36]:
# 11. Array Creation:
# Create a 2D NumPy array of shape (3, 3) with random integers between 0 and 9.

arr = np.random.randint(0, 9, size = (3, 3))
print(arr)

[[6 8 5]
 [8 7 4]
 [6 1 3]]


In [44]:
# 12. Array Broadcasting:
# Given a 1D array a = np.array([1, 2, 3]), add a scalar value 5 to each element using broadcasting.
# a = np.array([1, 2, 3])
print(np.shape(arr))

(3, 3)
