In [5]:
# create array 

import numpy as np

x = np.array([10, 20, 30, 40])
print(x)
print(type(x))


[10 20 30 40]
<class 'numpy.ndarray'>


In [8]:
# 2D array
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 3D array
import numpy as np

x = np.array([[[1,2], [4,5]], [[7,8], [9, 10]]])
print(x)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]


In [12]:
# we are creating the array with any data type --->with float data type

import numpy as np

x = np.array([10, 20, 30, 40], dtype = 'float')
print(x)
print(type(x))


[10. 20. 30. 40.]
<class 'numpy.ndarray'>


In [14]:
# we are creating the array with bool data type

import numpy as np

x = np.array([10, 0, 30, 40], dtype = 'bool')
print(x)
print(type(x))


[ True False  True  True]
<class 'numpy.ndarray'>


In [16]:
# creating the array within the range

import numpy as np

x = np.arange(1, 10)
print(x)
print(type(x))


[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [18]:
# creating the array within the range with step

import numpy as np

x = np.arange(1, 10, 2)
print(x)
print(type(x))


[1 3 5 7 9]
<class 'numpy.ndarray'>


In [20]:
# creating the array within the range with step

import numpy as np

x = np.arange(0, 11, 5)
print(x)
print(type(x))


[ 0  5 10]
<class 'numpy.ndarray'>


In [27]:
# creating the array within the range and rechange

import numpy as np

x = np.arange(1, 11)
print(x)

y = x.reshape(2,5)
z = x.reshape(5, 2)
print(y)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [30]:
# ones function
import numpy as np

x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
 # zeros function
import numpy as np

x = np.zeros((3, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# random numbers
import numpy as np

x = np.random.random((3, 3))
print(x)

[[0.13832904 0.90407642 0.04494117]
 [0.52761363 0.12477933 0.23071527]
 [0.17523398 0.10049527 0.46472702]]


In [35]:
# linspace
import numpy as np

x = np.linspace(10, 100, 10)
print(x)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [37]:
# identity
import numpy as np

x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
# Attributes of array

import numpy as np

a1 = np.arange(10)
a2 = a1.reshape(2, 5)
a3 = np.arange(12).reshape(2, 2, 3) 

print("a1 = ", a1, "\n")
print("a2 = ", a2, "\n")
print("a3 = ", a3, "\n")

a1 =  [0 1 2 3 4 5 6 7 8 9] 

a2 =  [[0 1 2 3 4]
 [5 6 7 8 9]] 

a3 =  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 



In [50]:
# find dimantions
a2.ndim

2

In [55]:
# shape (show how many rows and column in array)
a2.shape


(2, 5)

In [59]:
# how muche elements are in the array
a3.size

12

In [66]:
# size of the each element inside the array
a1.itemsize

8

In [68]:
# data type
a1.dtype

dtype('int64')

In [108]:
# changing data type
# astype
import numpy as np
a3 = np.array([11.2, 11.3])
a3.astype(np.int32)
a3


array([11.2, 11.3])

In [82]:
import numpy as np

arr = np.array([10.5, 11.5, 12.5, 13.5, 14.5])
print(arr)
print(arr.dtype)

print("After changing the data type")
arr.astype(np.int32)

[10.5 11.5 12.5 13.5 14.5]
float64
After changing the data type


array([10, 11, 12, 13, 14], dtype=int32)

In [97]:
# array operations

import numpy as np
arr1 = np.arange(12).reshape(3, 4)
arr2 = np.arange(12, 24).reshape(3, 4)

In [89]:
arr1 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [91]:
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [100]:
arr1 > 6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [99]:
# vector operations (operation on the two array)
#  arthimetic operations

In [101]:
arr1 + arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [102]:
arr1 * arr2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [109]:
arr1 - arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [110]:
arr1 / arr2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [118]:
# linspace
import numpy as np

x = np.arange(10).reshape((2, 5))
x.shape

(2, 5)

In [1]:
# functions 
# max / min / sum / prod
import numpy as np

x = np.arange(6).reshape((2, 3))
y = np.arange(6).reshape((3, 2))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
np.max(x)

8

In [4]:
# if i'll give the axis 0 column, 1 rows
np.max(x, axis = 1)

array([2, 5, 8])

In [7]:
# dot
x = np.arange(6).reshape((2, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[10, 13],
       [28, 40]])