In [68]:
import numpy as np

#  array creations
arr1 = np.array([1, 2, 3, 4, 5])

# arange
arr2 = np.arange(10)

# random
arr3 = np.random.random((3, 4))

# zeros
arr4 = np.zeros((3, 3))

# ones
arr5 = np.ones((3, 3))

# indentity
arr6 = np.identity(3)

# linspace
arr7 = np.linspace(10, 100, 5)

In [30]:
# check the data type

print(arr1.dtype)

int64


In [41]:
import numpy as np

# check the data type
print(arr1.dtype)

# change data type
arr1 = arr1.astype('int')
print(arr1.dtype)

float64
int64


In [45]:
# Attributes
# ndim / size / shape / astype / itemsize

# ndim (It show arrays' dimntions like 2D, 3D)
np.ndim(arr1)

5

In [46]:
# size (how much elements are in the array)
np.size(arr1)

5

In [48]:
# shape (how many rows and columns)
np.shape(arr1)

(3, 4)

In [71]:
# itemsize
arr1.itemsize

8

In [72]:
# operations






# perfome mathematical operations on the array

In [82]:
# indexing and sclicing
a1 = np.arange(10)
a2 = np.arange(9).reshape(3, 3)
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [84]:
# indexing on 1D array
a1[6]

6

In [89]:
# scling on 1D array
print(a1[3:])

[3 4 5 6 7 8 9]


In [91]:
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [94]:
# indexing on 2D
print(a2[2, 2])

8


In [98]:
# scling on 2D array
print(a2[1:, 1:3])

[[4 5]
 [7 8]]


In [100]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [118]:
temp = np.arange(12).reshape(3,4)
print(temp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [119]:
print(temp[::2, ::2])

[[ 0  2]
 [ 8 10]]


In [120]:
print(temp[1, ::3])

[4 7]


In [121]:
print(temp[:2, 1:])

[[1 2 3]
 [5 6 7]]


In [101]:

# indexing on 3D

print(a3[1, 0, 1])

5


In [102]:
# scling on 3D array
print(a3[:, 0, :])

[[0 1]
 [4 5]]


In [104]:
print(a2[::2, 1::2])

[[1]
 [7]]


In [124]:
# practice array
import numpy as np
arr1 = np.arange(27).reshape(3, 3, 3)
print(arr1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [125]:
print(arr1[1, :, :])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [128]:
print(arr1[::2, :, :])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [131]:
print(arr1[0, 1, :])

[3 4 5]


In [132]:
print(arr1[1, :, 1])

[10 13 16]


In [133]:
print(arr1[2, 1:3, 1:])

[[22 23]
 [25 26]]


In [134]:
print(arr1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [135]:
print(arr1[::2, 0, ::2])

[[ 0  2]
 [18 20]]


In [ ]:
print(arr1[::2, 0, ::2])

In [140]:
# iterating

In [142]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [144]:
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [145]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [146]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [147]:
# print 1 row at a time in 2D array
for i in a2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [148]:
# print 2D array at a time in 3D array
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [149]:
# when we want to iterate all the elements

for item in np.nditer(a3):
    print(item)

0
1
2
3
4
5
6
7


In [153]:
# split
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [156]:
# Horizantal
import numpy as np
np.hsplit(arr, 4)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# varical